import type { Metadata } from "next";
import "@/app/globals.css";
import Providers from "@/app/(public)/cart/providers";
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main><Header/>
                    {children}
                  <Footer/></main>
        </Providers>
      </body>
    </html>
  );
}
