import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/(public)/cart/providers";
import BackToTopButton from "@/components/ui/BackToTopButton";

export const metadata: Metadata = {
  title: "dunki",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <BackToTopButton />
        </Providers>
      </body>
    </html>
  );
}
