import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/(public)/cart/providers";
import BackToTopButton from "@/components/ui/BackToTopButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>{children}<BackToTopButton /></main>
        </Providers>
      </body>
    </html>
  );
}
