import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/app/(public)/cart/providers";
import BackToTopButton from "@/components/ui/BackToTopButton";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "dunki",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <BackToTopButton />
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#333",
                color: "#fff",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
